#!/usr/bin/env python
import rospy
from std_msgs.msg import String


def callback(data):
    # im feeling lazy today.
    pass


def listener():
    rospy.init_node('mole')
    rospy.Subscriber("once_upon_1984", String, callback)
    print("listening..")
    rospy.spin()


listener()
