#!/usr/bin/env python

import rospy
from std_msgs.msg import String


def talker():
    pub = rospy.Publisher('once_upon_1984', String, queue_size=10)
    rospy.init_node('snake', log_level=rospy.DEBUG)

    print "publishing.."

    # in seconds
    timeout = 0.01

    while not rospy.is_shutdown():
        pub.publish("im a snake.")
        rospy.sleep(timeout)
    print "done."

if __name__ == '__main__':
    talker()
