# get all statistics where timestamp in ms is > than timestamp
time timestamp
---
# each statistic has its own rated statistic. 
# timestamps can be found at the time windows of each statistic

HostStatistics[] host_statistics
RatedStatistics[] rated_host_statistics

NodeStatistics[] node_statistics
RatedStatistics[] rated_node_statistics

rosgraph_msgs/TopicStatistics[] topic_statistics
RatedStatistics[] rated_topic_statistics