#!/usr/bin/env python
import rospy
from arni_nodeinterface.host_statistics_handler import *
import os


def main():

    # howto ROS_IP ?
    ip = os.getenv('ROS_IP', '127.0.0.1')

    rospy.init_node("host_manager_%s" %
                    ip.replace('.', '_'), log_level=rospy.DEBUG)

    host = HostStatisticsHandler(ip)

    try:
        rospy.sleep(rospy.Duration(1))
        rospy.Timer(
            rospy.Duration(host.check_enabled_interval), host.check_enabled)
        rospy.Timer(rospy.Duration(host.update_interval), host.measure_status)
        rospy.Timer(
            rospy.Duration(host.publish_interval), host.publish_status)
        rospy.Timer(rospy.Duration(host.search_nodes_inv), host.get_node_info)
        while not rospy.is_shutdown():
            rospy.spin()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
